export type contactFormType = {
    firstName:string,
    lastName:string,
    email:string,
    phoneNumber:string,
    bsmm?:boolean,
    seo?:boolean,
    brm?:boolean,
    em?:boolean,
    gd?:boolean,
    wd?:boolean,
    other?:boolean,
    message:string,
    data?:string
    submittedOn?:string,
    _id?:string,
  }

export type contactPagePropsType = {
  title:string,
  description:string,
  features:string[],
  buttonText:string,
    contactForm:{
      fields:{
        firstName:{
          label:string,
          placeholder:string
        },
        lastName:{
          label:string,
          placeholder:string
        },
        email:{
          label:string,
          placeholder:string
        },
        phoneNumber:{
          label:string,
          placeholder:string
        },
        message:{
          label:string,
          placeholder:string
        }
      },
      serviceOptions:{
        title:string,
        options:string[]
      },
      submitButton:string,
    },
  contactInfo:{
    title:string,
    illustration:string,
  },
  socialSection:{
    title:string,
    platforms:string[]
  }
}